### PR TITLE
add example

### PR DESCRIPTION
**Pull request by Velua**

### CODE REVIEW

**Comment by Velua** [comment]
Screenshot from 2022-07-29 08-05-40

I like the spacing better on this one though now the Violet Garden photo in the 1st card is made too small, I suppose they should be more equal.

**Comment by behilam** [comment]
image

How about now?

**Comment by behilam** [comment]
image

With image sizes fixed

**Comment by behilam** [comment]
cardPreviewsWithLinks

Links for preview cards are working

**Pull request merged**
